version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3.13"
  jobs:
    create_environment:
      - asdf plugin add uv
      - asdf install uv latest
      - asdf global uv latest
    install:
      - uv sync --group docs --all-extras --no-extra mock-backport
    build:
      html:
        - uv run sphinx-build --fail-on-warning -T -b html docs $READTHEDOCS_OUTPUT/html
