version: 2

build:
  os: ubuntu-22.04
  tools:
    # https://github.com/sphinx-doc/sphinx/issues/13178 - waiting for Sphinx 8.2
    python: "3.12"

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs
sphinx:
  fail_on_warning: true
  configuration: docs/conf.py
