version: 2

build:
  os: ubuntu-24.04
  commands:
  - asdf plugin add uv
  - asdf install uv latest
  - asdf global uv latest
  - uv sync --group docs --all-extras --no-extra mock-backport
  - uv run sphinx-build --fail-on-warning -T -b html docs $READTHEDOCS_OUTPUT/html
